### ISSUE TITLE
Add support for 32 bit signed/unsigned integers

### ISSUE THREAD

**Issue by amirgol** [tim-hellhake/modbus-adapter#4]
Hi @tim-hellhake 
Is it possible to add configuration for merging two or more registers for one parameter(32-bit integer)? Or help me how can I add this configuration to it?
For example, most of the flowmeters send "total flow" parameter in two registers.
• Reg 114 High Word Total flow 
• Reg 115 Low Word Total flow
the real value calculated like below:
((Adr.114*65536)+Adr.115)
It will be best if it has the option to select the parameter signed or unsigned.

**Comment by tim-hellhake** [comment]
> Is it possible to add configuration for merging two or more registers for one parameter(32-bit integer)?

Sure, I'll add it.

**Comment by tim-hellhake** [comment]
@amirgol does it work? :smile:

**Comment by tim-hellhake** [comment]
I'm closing this now.
If it doesn't work, feel free to open a new issue.
