### ISSUE TITLE
Modbus Server

### ISSUE THREAD

**Issue by double-ee** [tim-hellhake/modbus-adapter#6]
Can you add Modbus server functionality to this?  It works great as a Modbus client, but I'm trying to read from my gateway using HMI software that will read from a Modbus server..

**Comment by tim-hellhake** [comment]
Sounds like a good idea.
What data types can your HMI display decode?

**Comment by double-ee** [comment]
I'm using Ignition Maker Edition, which looks like it will speak just about every function code ModbusTCP has.  I'm really just interested in discrete and analog values though.  Function codes 01 (Coil Status), 02 (Input Status), 03 (Holding Registers) and 04 (Input Registers).  For data types: bits, 16 and 32 bit integers, and 32 bit floating point.

**Comment by tim-hellhake** [comment]
I create a new addon called `modbus-bridge`.
It only supports read-only 1-bit and 16-bit integer registers at the moment.
Can you please check if it works with your HMI?

**Comment by double-ee** [comment]
Hi Tim!  Wow thanks!!  I added the modbus-bridge add on and tested it with the Modbus Tools Modbus Poll simulator.  I had mixed results.  I've added an issue to the modbus-bridge repository with more details.

**Comment by tim-hellhake** [comment]
> Hi Tim! Wow thanks!!

Glad you like it :)
Let us continue the conversation over there.
